.TH TRACE 1
.SH NAME
trace \- Small application for tracing a net path.
.SH SYNOPSIS
.B trace
[\fB\-f\fR \fIFIRST_TTL\fR]
[\fB\-m\fR \fIMAX_TTL\fR]
.IR address
.SH DESCRIPTION
.B trace
tracks the route packets taken from an IP network on their way to a given host.
It's uses UDP protocol for sending ICMP packets to host with incrementing TTL of each packet.
.PP
In case of errors host, network, protocol unreachable and communication administratively prohibited, the symbols H!, N!, P!, X! will be written accordingly.
.PP
In case of timeout, appropriate row will be marked with '*'.
.TP
Possible output can look like this:
  trace 8.8.8.8
  1   bda-boz.fit.vutbr.cz (147.229.176.1)   0.515 ms
  2   pe-meo.net.vutbr.cz (147.229.254.217)   1.060 ms
  3   pe-ant.net.vutbr.cz (147.229.252.90)   0.854 ms
  4   rt-ant.net.vutbr.cz (147.229.253.233)   0.155 ms
  5   r98-bm.cesnet.cz (147.229.252.17)   0.650 ms
  6   195.113.235.109 (195.113.235.109)   5.371 ms
  7   r2-r93.cesnet.cz (195.113.157.70)   5.258 ms
  8   108.170.245.33   4.871 ms
  9   108.170.235.149   5.210 ms
 10   google-public-dns-a.google.com (8.8.8.8)   4.897 ms
.SH OPTIONS
.TP
.BR -f \ \fIFIRST_TTL\fR
Specifies what TTL to use for the first packet. Default value is 1.
.TP
.BR -m \ \fIMAX_TTL\fR
Specifies maximum TTL value for packets. Default value is 30.
.TP
.BR address
IPV4/IPV6 host address.
.SH EXAMPLES
To trace path to google.com use:
.PP
.nf
.RS
\fBtrace\fR www.google.com
.RE
.fi
.PP
To trace path to address 172.217.23.238 with  first TTL 3 use:
.PP
.nf
.RS
\fBtrace\fR -f 3 172.217.23.238
.RE
.fi
.PP
To trace path to 2a00:1450:400d:802::1000 with max TTL 10 use:
.PP
.nf
.RS
\fBtrace\fR -m 10 2a00:1450:400d:802::1000
.RE
.fi
.SH SEE ALSO
.BR traceroute "(8), " tracepath "(8), " ping "(8)."
